[project]
name = "lh2pac"
authors = [
    {name = "Matthias De Lozzo", email = "matthias.delozzo@irt-saintexupery.com"}
]
description = "An academic project to design a liquid hydrogen powered aircraft."
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dynamic = ["version"]
requires-python = ">=3.10, <3.13"
dependencies = [
    "gemseo[all] == 6.3.1",
    "gemseo-oad-training @ git+https://gitlab.com/gemseo/dev/gemseo-oad-training.git@develop",
    "gemseo-mlearning == 3.1.0",
    "gemseo-umdo == 4.3.0",
    "properdocs",
    "black",
    "griffe-inherited-docstrings",
    "mkdocs-bibtex",
    "mkdocs-gallery",
    "mkdocs-gen-files",
    "mkdocs-include-markdown-plugin",
    "mkdocs-literate-nav",
    "mkdocs-material",
    "mkdocs-section-index",
    "mkdocstrings[python]",
    "tabulate",
]

[project.urls]
Homepage = "https://gitlab.com/MatthiasDeLozzo/lh2pac"
Source = "https://gitlab.com/MatthiasDeLozzo/lh2pac"
Tracker = "https://gitlab.com/MatthiasDeLozzo/lh2pac/-/issues"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[build-system]
requires = [
    "setuptools",
    "setuptools_scm[toml]",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
